kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      deployment: mongo
  template:
    metadata:
      labels:
        app: mongo
        deployment: mongo
    spec:
      volumes:
      - name: mongo-volume-1
        emptyDir: {}
      - name: mongo-volume-2
        emptyDir: {}
      containers:
      - name: mongo
        resources: {}
        ports:
        - containerPort: 27017
          protocol: TCP
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: mongo-volume-1
          mountPath: /data/configdb
        - name: mongo-volume-2
          mountPath: /data/db
        livenessProbe:
          initialDelaySeconds: 30
          tcpSocket:
            port: 27017
          timeoutSeconds: 1
        readinessProbe:
          initialDelaySeconds: 30
          tcpSocket:
            port: 27017
          timeoutSeconds: 1
        terminationMessagePolicy: File
        terminationMessagePath: /dev/termination-log
        image: quay.io/debezium/example-mongodb:latest
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
    deployment: mongo
  ports:
  - name: db
    port: 27017
    targetPort: 27017
